
package server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSTestImplService", targetNamespace = "http://server/", wsdlLocation = "http://192.168.1.157:8989/webService/server?wsdl")
public class WSTestImplService
    extends Service
{

    private final static URL WSTESTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSTESTIMPLSERVICE_EXCEPTION;
    private final static QName WSTESTIMPLSERVICE_QNAME = new QName("http://server/", "WSTestImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.157:8989/webService/server?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSTESTIMPLSERVICE_WSDL_LOCATION = url;
        WSTESTIMPLSERVICE_EXCEPTION = e;
    }

    public WSTestImplService() {
        super(__getWsdlLocation(), WSTESTIMPLSERVICE_QNAME);
    }

    public WSTestImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSTESTIMPLSERVICE_QNAME, features);
    }

    public WSTestImplService(URL wsdlLocation) {
        super(wsdlLocation, WSTESTIMPLSERVICE_QNAME);
    }

    public WSTestImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSTESTIMPLSERVICE_QNAME, features);
    }

    public WSTestImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSTestImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSTestImpl
     */
    @WebEndpoint(name = "WSTestImplPort")
    public WSTestImpl getWSTestImplPort() {
        return super.getPort(new QName("http://server/", "WSTestImplPort"), WSTestImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSTestImpl
     */
    @WebEndpoint(name = "WSTestImplPort")
    public WSTestImpl getWSTestImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "WSTestImplPort"), WSTestImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSTESTIMPLSERVICE_EXCEPTION!= null) {
            throw WSTESTIMPLSERVICE_EXCEPTION;
        }
        return WSTESTIMPLSERVICE_WSDL_LOCATION;
    }

}
